### ISSUE TITLE
错误: 缺少 JavaFX 运行时组件, 需要使用该组件来运行此应用程序

### ISSUE THREAD

**Issue by zlgxzswjy** [safe6Sec/ShiroExp#1]
release包 使用java -jar ShiroExp.jar时提示缺少JavaFX

**Comment by safe6Sec** [comment]
高版本jdk把javafx移除了，推荐用1.8来跑

**Comment by safe6Sec** [comment]
> release包 使用java -jar ShiroExp.jar时提示缺少JavaFX

高版本jdk把javafx移除了，推荐用1.8来跑

**Comment by Xc1Ym** [comment]
you can watch the issues of Behinder<https://github.com/rebeyond/Behinder/issues/115>

**Comment by 11snk** [comment]
jdk爸爸需要多少，我的版本打开就闪退

**Comment by 11snk** [comment]
jdk版本需要多少，我的版本打开就闪退

**Comment by Crany-web** [comment]
OS:Arch Linux
Java version：20.0.2
run command：`java --module-path "/home/crany/Desktop/javafx-sdk-20.0.2/lib" --add-modules javafx.controls,javafx.fxml -jar ShiroExp-1.3.1-all.jar`
https://blog.csdn.net/weixin_44746306/article/details/117768300
